travis:
  secure:
    BINSTAR_TOKEN: hD1fOgNE7aPlcoR+SosHkWRCHwZh/khgKJvFU8fZ1y/BC7/DY2+Yqr7I69LSqj8UFbClKiSe1Ad6dQsbYw/xWUh+QxPRF/9/yC0Rp+LLZCnFESQyTQR99YZdHjg2ssPLFjZPnei5mNRcsAtVbOD4qY89pjDGDAxcCGajTAJ/sJ8cJltkClEqgyrGQE2IMs3VlgCYsm0YMotB9hcvvvEbOKx028hN2Me/sLC4IQlCwhW7VAV7aLxacSnW0JPo6ZX4fM0BG8GLLS1Wr5hMo/NtppMxj7DhsaHi2rizVXn4PSQ7msYyFYeso6CBs7TIOl8fZ2aVLBgmgDqcA0vMdpwNBmKIrdkfsgTHR5xE9ZVjl88E3X+4WSWnm/a6/6SGDv2RbP8pm6GldTrkpTfrLfr9jK1xzD94fcewb7/JL/VYO4BIKgn+Q3kZIWSUiYvKmsyQZwOfGZPrBYkXc92txuuG6CGfxNStAFPy7LH+4MmUWAi22Q11f+B7MMkb47dK8nqWUZ0h3G49TkRCUa6Fuvb95pum6NGbqL3xDb3L+7clWnN2D2b+HwkR0vDRsONjHLX9COtpZbYzkvv7IWZEW0/+LpmLSQGZIIOCqXNQ1WDT/old7JyeuWOsVFRX7EII1kZSgjybiVUOk3ArKPsTuTC1yqEfR9k1RnZUdpMfD5mGvMw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
